=== mikevoxcap/messaging-patterns-pluralsight/src/main/java/com/pluralsight/patterns/messaging/documentmessage/Invoice.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema targetNamespace="http://www.pluralsight.com/patterns/messaging/Invoice" 
	attributeFormDefault="unqualified" 
	elementFormDefault="qualified" 
	xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="invoices">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="invoice" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:byte" name="invoiceNumber"/>
              <xs:element name="patient">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="name"/>
                    <xs:element type="xs:short" name="memberId"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="procedures">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="procedure" maxOccurs="unbounded" minOccurs="0">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element type="xs:short" name="code"/>
                          <xs:element type="xs:string" name="name"/>
                          <xs:element type="xs:float" name="cost"/>
                          <xs:element type="xs:float" name="insuranceEstimate"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== mikevoxcap/messaging-patterns-pluralsight/src/main/java/com/pluralsight/patterns/messaging/documentmessage/Invoice.xml
<?xml version="1.0" encoding="UTF-8"?>
<i:invoices 
	xmlns:i="http://www.pluralsight.com/patterns/messaging/Invoice" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://www.pluralsight.com/patterns/messaging/Invoice Invoice.xsd ">
	<i:invoice>
		<i:invoiceNumber>1</i:invoiceNumber>
		<i:patient>
			<i:name>Homer Simpson</i:name>
			<i:memberId>12345</i:memberId>
		</i:patient>
		<i:procedures>
			<i:procedure>
				<i:code>884</i:code>
				<i:name>Ear cleaning</i:name>
				<i:cost>40.00</i:cost>
				<i:insuranceEstimate>40.00</i:insuranceEstimate>
			</i:procedure>
			<i:procedure>
				<i:code>351</i:code>
				<i:name>X-ray</i:name>
				<i:cost>221.00</i:cost>
				<i:insuranceEstimate>100.00</i:insuranceEstimate>
			</i:procedure>
		</i:procedures>
	</i:invoice>
	<i:invoice>
		<i:invoiceNumber>2</i:invoiceNumber>
		<i:patient>
			<i:name>Bart Simpson</i:name>
			<i:memberId>12346</i:memberId>
		</i:patient>
		<i:procedures>
			<i:procedure>
				<i:code>152</i:code>
				<i:name>Removal of object from nose cavity</i:name>
				<i:cost>300.00</i:cost>
				<i:insuranceEstimate>140.00</i:insuranceEstimate>
			</i:procedure>
		</i:procedures>
	</i:invoice>
</i:invoices>
